epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: 0.0.0.0:40772

channels:
  - name: MX
    type: GR
    channel: '20'
  - name: CX
    type: GR
    channel: '21'
  - name: TBS
    type: GR
    channel: '22'
  - name: TX
    type: GR
    channel: '23'
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: ETV
    type: GR
    channel: '26'
  - name: NHK
    type: GR
    channel: '27'

tuners:
  - name: PX-Q1UD-1_0
    types: [GR]
    command: >-
      recdvb --dev 0 {{channel}} {{duration}} -
  - name: PX-Q1UD-1_1
    types: [GR]
    command: >-
      recdvb --dev 1 {{channel}} {{duration}} -
  - name: PX-Q1UD-1_2
    types: [GR]
    command: >-
      recdvb --dev 2 {{channel}} {{duration}} -
  - name: PX-Q1UD-1_3
    types: [GR]
    command: >-
      recdvb --dev 3 {{channel}} {{duration}} -

filters:
  decode-filter:
    command: >-
      arib-b25-stream-test
